steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-west1-docker.pkg.dev/proj-2025-nov-08-gemini-hackathon/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'
      - '.'
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/proj-2025-nov-08-gemini-hackathon/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '$_SERVICE_NAME'
      - '--image'
      - 'us-west1-docker.pkg.dev/proj-2025-nov-08-gemini-hackathon/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'
      - '--region'
      - '$_DEPLOY_REGION'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'us-west1-docker.pkg.dev/proj-2025-nov-08-gemini-hackathon/$_AR_REPOSITORY/$_SERVICE_NAME:$SHORT_SHA'
